name: app_utils
description: Application  plugin which provides utility functions for Android and iOS.
repository: https://github.com/vishesh005/app_utils
issue_tracker: https://github.com/vishesh005/app_utils/issues?q=is%3Aissue+is%3Aopen
version: 0.0.8
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: in.techbyvishesh.app_utils
        pluginClass: AppUtilsPlugin
      ios:
        pluginClass: AppUtilsPlugin

