name: App Util Plugin Publish


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        run: echo "${INPUT_PACKAGE_DIRECTORY}/credentials.json"
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          package_directory: "."
          flutter_package: false
          skip_test: true
          dry_run: false

